src/views/home.py
from flask import Blueprint,request,render_template,jsonify
from src.db import QuearyExe
from flask_socketio import emit

query = QuearyExe()
home_bp = Blueprint("home",__name__)

from ..flask_app import socket

@home_bp.route("/", methods=['GET'])
def home():
    query = QuearyExe()
    res = query.getTiltleSponser()
    print("re",res)
    stadiums = query.Stduim_details()
    print("st",stadiums)
    return render_template("index.html",stadiums=stadiums ,title_sponsors=res)

@home_bp.route('/titleSponser', methods=['GET'])
def titleSponser():
    query = QuearyExe()
    res = query.getTiltleSponser()
    return res
    # return render_template("index.html",res)

@home_bp.route('/player', methods=['GET'])
def players():
    query = QuearyExe()
    team_name = request.args.get('team')
    res = query.Player_details_by_name(team_name)
    print("pop",res)
    return render_template("player info.html",data = res)



@socket.on("search_player_by_name")
def player_by_name():
    pass

src/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>IPL Insights</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="static/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="static/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="static/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="static/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="static/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="static/css/style.css" rel="stylesheet">


<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-transparent">
    <div class="container">

      <div class="logo float-left">
        <h1 class="text-light"><a href="index.html"><span>Cric Analyzer</span></a></h1>
      </div>

      <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="#hero">Home</a></li>
          <li><a href="#about">About Us</a></li>
          <li><a href="#services">Stadium Details</a></li>
          <li><a href="#contact">Title Sponsor</a></li>
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex justify-cntent-center align-items-center">
    <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">

      <!-- Slide 1 -->
      <div class="carousel-item active">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Welcome to <span>Cric Analyzer </span></h2>
          <p class="animated fadeInUp">Cric Analyser is your comprehensive platform for all things cricket. Whether you're a passionate fan, a fantasy league enthusiast, or a data-driven analyst, we've got you covered. Dive into the world of cricket with our rich database of player statistics, match analysis, and team performance insights. Stay updated with live scores, news highlights, and expert commentary. With intuitive tools and interactive features, Cric Analyser empowers you to explore the game like never before. From in-depth player profiles to strategic match predictions, we provide the tools and information you need to elevate your cricket experience to the next level.</p>
          <a href="" class="btn-get-started animated fadeInUp">Read More</a>
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Designed By</h2>
          <p class="animated fadeInUp"> 
            Arijit Ghosal (11200221003)<br>
            Shehenaz Islam (11200221011)<br>
            SK Nasir Hossain (11200221012)<br>
            SK Murshid Alam (11200221013)
          </p>
          <a href="" class="btn-get-started animated fadeInUp">Read More</a>
        </div>
      </div>

      <!-- Slide 3 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Get Player Insights</h2>
          <p class="animated fadeInUp">Explore player profiles effortlessly with our advanced search feature. Simply enter a player's name and uncover comprehensive details, including statistics, achievements, and career highlights. Whether you're scouting for fantasy leagues or analyzing performance trends, our intuitive search tool delivers precise and insightful player information at your fingertips.</p>
          <a href="" class="btn-get-started animated fadeInUp">Read More</a>
        </div>
      </div>
       <!-- Slide 4 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animated fadeInDown">Other Insights (Stadium and Title Sponsor)</h2>
          <p class="animated fadeInUp"> Discover more about the stadiums and title sponsors with our comprehensive feature. Explore key insights into the iconic venues where cricket history is made and learn about the brands that support the sport. From capacity and amenities to sponsorship deals, delve into the heart of cricket culture and its corporate partnerships with ease.</p>
          <a href="" class="btn-get-started animated fadeInUp">Read More</a>
        </div>
      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= ABout Section ======= -->
    <section id="about">
      <div class="container">
        <h2 class="animated fadeInDown">About Us</h2>
        <div class="row">
          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up">
            <div class="icon-box icon-box-pink">
              <div class="icon"><i class="bx bx-rocket icon"></i></div>
              <h4 class="title"><a href="">Provides IPL insights</a></h4>
              <p class="description">We provide details of IPL 2022 containing player names for each team, Player Details, Stadium Details and Title Sponsors</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
            <div class="icon-box icon-box-cyan">
              <div class="icon"><i class="bx bx-group icon"></i></div>
              <h4 class="title"><a href="">Team Management</a></h4>
              <p class="description">Hii I am Arijit Ghosal, I designed the Frontend part of this website,with HTML,CSS and JS along with my friends Sk Murshid Alam who designed the backend part along with connecting with the database to the frontend, Sk Nasir Hossain who designed the complete database , ran queries for data retrieval, joining and other operations and Shehenaz Islam who was in charge of the presentation part for the complete project.</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
            <div class="icon-box icon-box-green">
              <div class="icon"><i class="bx bx-globe icon"></i></div>
              <h4 class="title"><a href="">Database</a></h4>
              <p class="description">The database consists of IPL insights from 2022  - Players Details , Player names from Six strong Teams , Stadium Details where the matches were played and Title Sponsors for Each Team</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
            <div class="icon-box icon-box-blue">
              <div class="icon"><i class="bx bx-shield icon"></i><br></div>
              <h4 class="title"><a href="">Privacy and Security</a></h4>
              <p class="description"> We prioritize the privacy and security of our website and Data, the database is kept securely and any changes in the frontend would not affect it, we are retrieving data using SQl queries, converting it to json fie and sending it to the frontend for display</p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Services Section -->

    <!-- ======= Why Us Section ======= -->
    <section class="why-us section-bg" data-aos="fade-up" date-aos-delay="200">
      <div class="container">

         
            <div class="container">
              <div class="info-box" style="background-image: url('https://possible11.s3.ap-south-1.amazonaws.com/blog/ipl-2022-delhi-capitals-reveal-their-new-jersey-ahead-of-the-season.jpg')">
                  <img src="{{ url_for('static', filename='images/DC.png') }}" alt="DC Logo" class="logo">
                  
                  <a href="{{ url_for('home.players', team='Gujarat Titans___') }}"" class="button-30">View Details</a>
              </div>
              <div class="info-box" style="background-image: url('https://images.indiafantasy.com/wp-content/uploads/20230218165321/Chennai-Super-Kings-poster-1.jpg')">
                  <img src="{{ url_for('static', filename='images/CSK.png') }}" alt="CSK Logo"class="logo">
                 
                  <a href="{{ url_for('home.players', team='Chennai Super Kings') }}" class="button-30">View Details</a>
              </div>
              <div class="info-box" style="background-image: url('https://www.sportzcraazy.com/wp-content/uploads/2021/02/Rajasthan-Royals-2021-Team-Preview.jpg')">
                  <img src="{{ url_for('static', filename='images/RR.png') }}" alt="RR Logo" class="logo">
                 
                  <a href="{{ url_for('home.players', team='Rajasthan Royals') }}" class="button-30">View Details</a>
              </div>
              <div class="info-box" style="background-image: url('https://images.indiafantasy.com/wp-content/uploads/20230228114736/KKR-Photo-768x337.jpg')">
                  <img src="{{ url_for('static', filename='images/KKR.png') }}" alt="KKR Logo" class="logo">
                 
                  <a href="{{ url_for('home.players', team='Kolkata Knight Riders') }}"class="button-30">View Details</a>
              </div>
              <div class="info-box" style="background-image: url('https://wallpapercave.com/wp/wp8984946.jpg')">
                  <img src="{{ url_for('static', filename='images/RCB.png') }}" alt="RCB Logo" class="logo">
                
                   <a href="{{ url_for('home.players', team='Royal Challengers Bangalore') }}" class="button-30">View Details</a>
              </div>
              <div class="info-box" style="background-image: url('https://wallpapercave.com/wp/wp7432594.jpg ')">
                  <img src="{{ url_for('static', filename='images/MI.png') }}" alt="MI Logo" class="logo">
                 
                  <a href="{{ url_for('home.players', team='Mumbai Indians') }}" class="button-30" id="viewDetailsBtn">View Details</a>
      
          </div>
        </div>

      </div>
    </section>

    <!-- ======= Services Section ======= -->
    <section id="services">
      <div class="container">

        <div class="section-title">
          <h2>Stadium Details</h2>
          <div class="container">
            {% for stadium in stadiums %}
            <div class="card">
              <h2>{{ stadium.StadiumName }}</h2>
              <p><strong>City:</strong> {{ stadium.City }}</p>
              <p><strong>Country:</strong> {{ stadium.Country }}</p>
              <p><strong>Capacity:</strong> {{ stadium.Capacity }}</p>
              <p><strong>Rent Amount:</strong> {{ stadium.RentAmount }}</p>
            </div>
            {% endfor %}
          </div>
          <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

            <div class="footer-newsletter">
              <div class="container">
                <div class="row">
                  <div class="col-lg-6">
                    <h4>Register</h4>
                    <p>Enter Email Id for details</p>
                  </div>
                  <div class="col-lg-6">
                    <form action="" method="post">
                      <input type="email" name="email"><input type="submit" value="Register">
                    </form>
                  </div>
                </div>
              </div>
            </div>

    <section id="contact">

    <div class="footer-top">
      <div class="container">
        <div class="row">

         

          <h2>Title Sponsors</h2>
          <div class="sponsor-cards">
            <div class="row">
                {% for sponsor in title_sponsors %}
                <div class="column">
                    <div class="sponsor-card">
                        <h3>{{ sponsor.CompanyName }}</h3>
                        <p><strong>Business Domain:</strong> {{ sponsor.BusinessDomain }}</p>
                        <p><strong>Country:</strong> {{ sponsor.Country }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        
    </section>

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="static/vendor/jquery/jquery.min.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="static/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="static/vendor/php-email-form/validate.js"></script>
  <script src="static/vendor/venobox/venobox.min.js"></script>
  <script src="static/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="static/vendor/counterup/counterup.min.js"></script>
  <script src="static/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="static/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="static/js/main.js"></script>

</body>

</html>

src/templates/player info.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Player Information</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='player info.css') }}">
</head>

<body>
    <div class="info-box" style="background-image: url('https://wallpapercave.com/wp/wp8994026.jpg');">
        <div class="info-item">
            <img src="{{ url_for('static', filename='images/ipl-logo-new-old.png') }}" alt="Delhi Capitals Logo">
        </div>
        <div class="info-item">

            <p></p>
        </div>
        <body>
            <div id="playerInfo" class ="player">
                {% for team, players in data.items() %}
                    <h2 >{{ team }}</h2>
                    <ul>
                        {% for player in players %}
                            <p >{{ player.Name }}</p>
                    
                        {% endfor %}
                    </ul>
                {% endfor %}
            </div>
        </body>
        
        <div class="info-item">
            <div id="playerInfo"></div>
            
            <button class="btn" onclick="redirectTocskhtml()">Back to page</button>
        </div>
    </div>
    <script>
        function redirectTocskhtml() {
    window.location.href = "/"; // Replace "index.html" with the path to your home page
}
        document.addEventListener("DOMContentLoaded", function() {
    const playerInfoDiv = document.getElementById("playerInfo");

    // Fetch player data from Flask view
    fetch("/players")
        .then(response => response.json())
        .then(data => {
            // Loop through teams in the JSON data
            Object.keys(data).forEach(team => {
                const players = data[team];
                // Loop through players in each team
                players.forEach(player => {
                    // Create a div element for each player's name
                    const playerDiv = document.createElement("div");
                    playerDiv.textContent = player.Name;
                    playerInfoDiv.appendChild(playerDiv);
                });
            });
        })
        .catch(error => console.error("Error fetching player data:", error));
});

    </script>
</body>

</html>